#! /bin/bash

printf "Work-Shop WordPress Remote Setup. (v1.0)\n"


cd /Applications/MAMP/htdocs
printf "What would you like to name your new WordPress root directory (i.e. mywpdir)? "
read NEWDIR
printf "Retrieving latest version of WordPress.\n"
git clone https://github.com/WordPress/WordPress.git $NEWDIR
cd $NEWDIR
rm -rf .git
cd ../

printf "Retrieving latest version of the Work-Shop WordPress Template.\n"
git clone https://github.com/work-shop/wp-template.git $NEWDIR-tmp
rm -rf $NEWDIR-tmp/.git
printf "Merging.\n"
cp -R $NEWDIR-tmp/wp-content/* $NEWDIR/wp-content/
cp -f $NEWDIR-tmp/utilities/wp-config.php $NEWDIR
mv $NEWDIR-tmp/utilities/instance.gitignore $NEWDIR/.gitignore
rm -rf $NEWDIR-tmp

cd $NEWDIR
git init
git add .
git commit -m "Initial commit"

printf "Enter the name of the shared database here: "
read SHAREDDB

printf "Enter the name of the mysql user for this database here: (\"root\" is default)"
read MYSQLUSR
if [ "$MYSQLUSER" = "" ]; then
	set MYSQLUSER = "root"
fi
printf "Enter the name of the mysql password for this database: (\"root\" is default)"
read MYSQLPASS
if [ "$MYSQLPWD" = "" ]; then
	set MYSQLPWD = "root"
fi

DBUSER=$"username_here"
DBPASS=$"password_here"
DBNAME=$"database_name_here"

sed -i '' -e "s/${DBUSER}/${MYSQLUSER}/g" wp-config.php
sed -i '' -e "s/${DBPASS}/${MYSQLPWD}/g" wp-config.php
sed -i '' -e "s/${DBNAME}/${NEWDB}/g" wp-config.php


open http://work-shop.ws/cpanel

